<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <InvariantGlobalization>true</InvariantGlobalization>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ClickHouse.Client" Version="6.0.0"/>
        <PackageReference Include="Confluent.Kafka" Version="2.3.0"/>
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" Version="9.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ChangeLogMonitor.Protos\ChangeLogMonitor.Protos.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Include="..\ChangeLogMonitor.DataAggregator\Models\TxAggregate.cs" Link="Models\TxAggregate.cs"/>
    </ItemGroup>

</Project>
