<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\ChangeLogMonitor.Core\ChangeLogMonitor.Core.csproj"/>
        <ProjectReference Include="..\ChangeLogMonitor.Configuration\ChangeLogMonitor.Configuration.csproj"/>
        <ProjectReference Include="..\ChangeLogMonitor.DataAggregator\ChangeLogMonitor.DataAggregator.csproj"/>
        <ProjectReference Include="..\ChangeLogMonitor.Finalization\ChangeLogMonitor.Finalization.csproj"/>
        <ProjectReference Include="..\ChangeLogMonitor.Protos\ChangeLogMonitor.Protos.csproj"/>
    </ItemGroup>

</Project>
