\connect
changelog

GRANT CONNECT ON DATABASE changelog TO debezium;
GRANT CREATE
ON DATABASE changelog TO debezium;
GRANT USAGE ON SCHEMA
public TO harness_app, debezium;
GRANT CREATE
ON SCHEMA public TO harness_app;

GRANT ALL PRIVILEGES ON ALL
TABLES IN SCHEMA public TO harness_app;
GRANT ALL PRIVILEGES ON ALL
SEQUENCES IN SCHEMA public TO harness_app;
ALTER
DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO harness_app;
ALTER
DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO harness_app;

GRANT
SELECT
ON ALL TABLES IN SCHEMA public TO debezium;
GRANT
SELECT
ON ALL SEQUENCES IN SCHEMA public TO debezium;
ALTER
DEFAULT PRIVILEGES IN SCHEMA public GRANT
SELECT
ON TABLES TO debezium;
ALTER
DEFAULT PRIVILEGES IN SCHEMA public GRANT
SELECT
ON SEQUENCES TO debezium;
ALTER
DEFAULT PRIVILEGES FOR ROLE harness_app IN SCHEMA public GRANT
SELECT
ON TABLES TO debezium;
ALTER
DEFAULT PRIVILEGES FOR ROLE harness_app IN SCHEMA public GRANT
SELECT
ON SEQUENCES TO debezium;
