<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\ChangeLogMonitor.Api\ChangeLogMonitor.Api.csproj"/>
        <ProjectReference Include="..\ChangeLogMonitor.UI\ChangeLogMonitor.UI.csproj"/>
        <ProjectReference Include="..\ChangeLogMonitor.DataAggregator\ChangeLogMonitor.DataAggregator.csproj"/>
        <ProjectReference Include="..\ChangeLogMonitor.Finalization\ChangeLogMonitor.Finalization.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="..\changelog-config.yaml" Link="changelog-config.yaml">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

</Project>
